### PR TITLE
Update dependencies

### LINKED ISSUE #97: Deprecated `octokit.hasNextPage`
There's a deprecated message whenever this is run:

`DEPRECATED (@octokit/rest): octokit.hasNextPage() – You can use octokit.paginate or async iterators instead: https://github.com/octokit/rest.js#pagination.`

Consider resolving it. Thanks!

### LINKED ISSUE #100: Deprecated `error.code`
```text
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/usr/lib/node_modules/remove-github-forks/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at /usr/lib/node_modules/remove-github-forks/src/shouldDeleteFork.js:35:21
    at /usr/lib/node_modules/remove-github-forks/src/githubFactory.js:75:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Deprecation'
```

### PR DESCRIPTION
**Pull request by fregante**
Fixes #97
Fixes #100

### CODE REVIEW

**Comment by fregante** [comment]
I tested this locally with `npx . #token#` and it works, but the tests are against the previous `@octokit/rest` interface rather than towards the API itself.

I tried looking into it but I don't know how to fix it.

**Review by denis-sokolov — COMMENTED** [review]
This is great, thank you for figuring out what has changed in octokit/rest. The amount of backwards incompatible changes they introduce is above what I’d consider average.

We need to either update the tests to match the new version or remove them altogether. I wouldn’t want inconsistent tests in the repo. I’ll take a look at them and choose something to proceed!

**Comment by fregante** [comment]
Once this is merged I'll also modernize the code if you don't mind, applying a [strict eslint config](https://github.com/xojs/xo) and running its auto-fixer will automatically cover most of this without changing how the code works.

**Comment by fregante** [comment]
Sorry for the many commits, I tried to resolve the merge conflicts as they appeared. We can "Squash and merge" PRs to have a cleaner history.

**Comment by fregante** [comment]
Awesome!

**Comment by denis-sokolov** [comment]
No problem about small commits, cleaning branches before merging is an easy chore for me.

Please refrain from working on this branch at the moment, I am finishing up tests and rewriting the branch a bit.

**Comment by denis-sokolov** [comment]
I’ve fixed the test and rewritten the branch. Thank you for making this!

**Comment by fregante** [comment]
I think your computer’s time is off because you commit in the future:

**Comment by denis-sokolov** [comment]
You’re the first notice! No, my clock is fine. :-) I shield my privacy by rounding all commits to noon of the day of the commit.

**Pull request merged**
