### PR TITLE
Add a couple of onRejected functions to avoid Node's UnhandledPromiseRejectionWarning. Fixes #47

### LINKED ISSUE #47: UnhandledPromiseRejectionWarning
While running I got the following error:
```
(node:87182) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): {"message":"Server Error: Sorry, this diff is taking too long to generate.","errors":[{"resource":"Comparison","field":"diff","code":"not_available"}],"documentation_url":"https://developer.github.com/v3/repos/commits/#compare-two-commits"}
(node:87182) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It is unclear which repo this was for, and it is unclear where that error is coming from.

### PR DESCRIPTION
**Pull request by bramp**

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Thanks for the fix! I have slightly reformatted it and manually merged into master, keeping your authorship.

**Comment by bramp** [comment]
Thanks Denis. No problem with reformatting, however Hound Bot was requiring a couple of my style changes.

Oh also you dropped the change in index.js. Was that intentional?

**Comment by denis-sokolov** [comment]
I've now disabled the Hound bot.

Most changes in `src/index.js` were cosmetic, and the only functional change only limited the error handler, in my understanding. Here's the change:

```js
promise.then(f).then(null, errorHandler);
promise.then(f, errorHandler);
```

The difference is in the second version, `errorHandler` does not handle errors that happened in `f`, and this seems a negative. Did I misunderstand your meaning, or maybe I am missing something?

**Comment by bramp** [comment]
TBH I had to read up on Promises to fix the UnhandledPromiseRejectionWarning, so I may also be missing something. But my understanding is the two examples are identical. I just chose the 2nd , since it was more compact. If I am mistaken then free feel to ignore, and (when I'm near my computer) I'll check the submitted code fixed things for me.

**Pull request closed without merging**
