### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by waldyrious**
- slight rewording of a couple passages, for clarity
- include sudo in the npm global install command

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Great, thank you!

**Comment by waldyrious** [comment]
Thank *you* for such a convenient tool!

**Comment by denis-sokolov** [comment]
I'm happy to hear you find it useful. :) It really should be a part of GitHub UI one way or another, in my opinion.

**Comment by waldyrious** [comment]
Ugh, that and so much more... resyncing forks, amending commits, rebasing PRs...

**Pull request merged**
