### PR TITLE
dont pass url to github api call as it breaks delete operation

### PR DESCRIPTION
**Pull request by pwielgolaski**
Fixes https://github.com/denis-sokolov/remove-github-forks/issues/62

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Thanks for your contribution!

Could you give me some more details how you found this, how exactly it behaves?
Could you give some logs or something, for future reference? Thanks!

**Comment by pwielgolaski** [comment]
What i did, I enabled DEBUG for git api and discovered that delete request was not set to api.github.com and did not start with /repos, but was send to github.com with path /:owner/:repo

I run it in Intelij and found place
https://github.com/octokit/rest.js/blob/v13.0.1/lib/index.js#L518
called from https://github.com/octokit/rest.js/blob/v13.0.1/lib/index.js#L607

So if you add url parameter it try to deduct host and url based on message url instead of using configuration.

**Comment by denis-sokolov** [comment]
Thank you for these details! I will look into this and figure it out.

**Comment by denis-sokolov** [comment]
Merged in 1.5.2, thank you!

**Pull request closed without merging**
